/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author trabajo
 */
public class Encargado extends javax.swing.JFrame {

    /**
     * Creates new form Principa
     */
    public Encargado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInterno = new javax.swing.JDesktopPane();
        jTortillasIcon = new javax.swing.JButton();
        jRellenosIcon = new javax.swing.JButton();
        jSalsasIcon = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jListadoIcon = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuIngredientes = new javax.swing.JMenu();
        jVerIngredientes = new javax.swing.JMenuItem();
        jTortilla = new javax.swing.JMenuItem();
        jRelleno = new javax.swing.JMenuItem();
        jSalsa = new javax.swing.JMenuItem();
        jMenuAbrir = new javax.swing.JMenu();
        jCargarPedido = new javax.swing.JMenuItem();
        jCocina = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTortillasIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/tortilla.png"))); // NOI18N
        jTortillasIcon.setBorder(null);
        jTortillasIcon.setBorderPainted(false);
        jTortillasIcon.setContentAreaFilled(false);
        jTortillasIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTortillasIcon.setFocusPainted(false);
        jTortillasIcon.setRolloverEnabled(false);

        jRellenosIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/relleno.fw.png"))); // NOI18N
        jRellenosIcon.setBorder(null);
        jRellenosIcon.setBorderPainted(false);
        jRellenosIcon.setContentAreaFilled(false);
        jRellenosIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRellenosIcon.setFocusPainted(false);
        jRellenosIcon.setRolloverEnabled(false);

        jSalsasIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/salsa.fw.png"))); // NOI18N
        jSalsasIcon.setBorder(null);
        jSalsasIcon.setBorderPainted(false);
        jSalsasIcon.setContentAreaFilled(false);
        jSalsasIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jSalsasIcon.setFocusPainted(false);
        jSalsasIcon.setRolloverEnabled(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("CARGA DE:");

        jListadoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Listado.fw.png"))); // NOI18N
        jListadoIcon.setBorder(null);
        jListadoIcon.setBorderPainted(false);
        jListadoIcon.setContentAreaFilled(false);
        jListadoIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jListadoIcon.setFocusPainted(false);
        jListadoIcon.setRolloverEnabled(false);

        jPanelInterno.setLayer(jTortillasIcon, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPanelInterno.setLayer(jRellenosIcon, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPanelInterno.setLayer(jSalsasIcon, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPanelInterno.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPanelInterno.setLayer(jListadoIcon, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanelInternoLayout = new javax.swing.GroupLayout(jPanelInterno);
        jPanelInterno.setLayout(jPanelInternoLayout);
        jPanelInternoLayout.setHorizontalGroup(
            jPanelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInternoLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addGroup(jPanelInternoLayout.createSequentialGroup()
                            .addComponent(jTortillasIcon)
                            .addGap(43, 43, 43)
                            .addComponent(jRellenosIcon)
                            .addGap(55, 55, 55)
                            .addComponent(jSalsasIcon))
                        .addComponent(jListadoIcon))
                    .addComponent(jLabel1))
                .addContainerGap(296, Short.MAX_VALUE))
        );
        jPanelInternoLayout.setVerticalGroup(
            jPanelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInternoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSalsasIcon)
                    .addComponent(jRellenosIcon)
                    .addComponent(jTortillasIcon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jListadoIcon)
                .addContainerGap())
        );

        jMenuIngredientes.setText("Ingredientes");

        jVerIngredientes.setText("Lista Ingredientes");
        jMenuIngredientes.add(jVerIngredientes);

        jTortilla.setText("Edicion Tortillas");
        jMenuIngredientes.add(jTortilla);

        jRelleno.setText("Edicion Rellenos");
        jMenuIngredientes.add(jRelleno);

        jSalsa.setText("Edicion Salsas");
        jMenuIngredientes.add(jSalsa);

        jMenuBar1.add(jMenuIngredientes);

        jMenuAbrir.setText("Abrir");

        jCargarPedido.setText("Modo Empleado");
        jCargarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCargarPedidoActionPerformed(evt);
            }
        });
        jMenuAbrir.add(jCargarPedido);

        jCocina.setText("Modo Cocina");
        jMenuAbrir.add(jCocina);

        jMenuBar1.add(jMenuAbrir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInterno)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInterno)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCargarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCargarPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCargarPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Encargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Encargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Encargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Encargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Encargado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem jCargarPedido;
    public javax.swing.JMenuItem jCocina;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JButton jListadoIcon;
    private javax.swing.JMenu jMenuAbrir;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenu jMenuIngredientes;
    public javax.swing.JDesktopPane jPanelInterno;
    public javax.swing.JMenuItem jRelleno;
    public javax.swing.JButton jRellenosIcon;
    public javax.swing.JMenuItem jSalsa;
    public javax.swing.JButton jSalsasIcon;
    public javax.swing.JMenuItem jTortilla;
    public javax.swing.JButton jTortillasIcon;
    public javax.swing.JMenuItem jVerIngredientes;
    // End of variables declaration//GEN-END:variables
}
