/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View.Internal.Pedidos;

import Model.Estados;

/**
 *
 * @author trabajo
 */
public class Internal_Cocina extends javax.swing.JInternalFrame {

    /**
     * Creates new form Internal_Cargar
     */
    public Internal_Cocina() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opciones = new javax.swing.ButtonGroup();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPedidosCocina = new javax.swing.JTable();
        jUpdateCocina = new javax.swing.JButton();
        jEstado = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboEstados = new javax.swing.JComboBox<>();
        jRadioDefecto = new javax.swing.JRadioButton();
        jRadioTodos = new javax.swing.JRadioButton();
        jRecarga = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        jCalendario = new com.toedter.calendar.JDateChooser();
        jRadioFiltrar = new javax.swing.JCheckBox();
        jRadioFecha = new javax.swing.JCheckBox();

        setTitle("Listado de Pedido");

        jPedidosCocina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Fecha", "Estado", "Tortilla", "Salsa", "Relleno 1", "Relleno 2", "Relleno 3"
            }
        ));
        jPedidosCocina.setShowGrid(true);
        jScrollPane4.setViewportView(jPedidosCocina);

        jUpdateCocina.setBackground(new java.awt.Color(102, 255, 0));
        jUpdateCocina.setText("Cambiar Estado");
        jUpdateCocina.setEnabled(false);
        jUpdateCocina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateCocinaActionPerformed(evt);
            }
        });

        jEstado.setMaximum(4);
        jEstado.setMinimum(1);
        jEstado.setMinorTickSpacing(1);
        jEstado.setPaintLabels(true);
        jEstado.setPaintTicks(true);
        jEstado.setSnapToTicks(true);

        jLabel1.setText("Pedido");

        jLabel2.setText("En Preparacion");

        jLabel3.setText("Para Retirar");

        jLabel4.setText("Entregado");

        jComboEstados.setEnabled(false);
        jComboEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboEstadosActionPerformed(evt);
            }
        });

        opciones.add(jRadioDefecto);
        jRadioDefecto.setText("Por Defecto");

        opciones.add(jRadioTodos);
        jRadioTodos.setText("Mostrar Todos");

        jRecarga.setForeground(new java.awt.Color(102, 255, 0));
        jRecarga.setMaximum(30);
        jRecarga.setString("0 seg");
        jRecarga.setStringPainted(true);

        jLabel5.setText("Actualizacion automatica en:");

        jRadioFiltrar.setText("Filtrar");
        jRadioFiltrar.setEnabled(false);
        jRadioFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioFiltrarActionPerformed(evt);
            }
        });

        jRadioFecha.setText("Fecha");
        jRadioFecha.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel1)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel2)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel3)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(jUpdateCocina)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioDefecto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioTodos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioFiltrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRecarga, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(28, 28, 28))))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioDefecto)
                                .addComponent(jRadioTodos))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jRadioFiltrar)
                                .addComponent(jRadioFecha))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRecarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jUpdateCocina)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jUpdateCocinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateCocinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUpdateCocinaActionPerformed

    private void jComboEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboEstadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboEstadosActionPerformed

    private void jRadioFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioFiltrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioFiltrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public com.toedter.calendar.JDateChooser jCalendario;
    public javax.swing.JComboBox<Estados> jComboEstados;
    public javax.swing.JSlider jEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JTable jPedidosCocina;
    public javax.swing.JRadioButton jRadioDefecto;
    public javax.swing.JCheckBox jRadioFecha;
    public javax.swing.JCheckBox jRadioFiltrar;
    public javax.swing.JRadioButton jRadioTodos;
    public javax.swing.JProgressBar jRecarga;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JButton jUpdateCocina;
    public javax.swing.ButtonGroup opciones;
    // End of variables declaration//GEN-END:variables
}
